export const membersData = [
    {
        email: "emily.walker@test.com",
        username: 'emily.walker',
        gender: "female",
        dateOfBirth: "1995-02-28",
        name: "Emily Walker",
        created: "2024-08-10",
        lastActive: "2024-09-04",
        description: "Emily is a nature conservationist who works with local nonprofits to preserve natural habitats. In her spare time, she enjoys birdwatching, painting landscapes, and spending time at her family’s cabin in the Rockies.",
        city: "Kelowna",
        country: "Canada",
        image: "/images/f1.jpeg"
    },
    {
        email: "amelia.davis@test.com",
        username: 'amelia.davis',
        gender: "female",
        dateOfBirth: "1996-07-04",
        name: "Amelia Davis",
        created: "2024-08-09",
        lastActive: "2024-08-29",
        description: "Amelia is a robotics engineer with a keen interest in artificial intelligence. Outside of work, she enjoys indoor rock climbing, writing sci-fi stories, and attending local hackathons.",
        city: "Victoria",
        country: "Canada",
        image: "/images/f2.jpeg"
    },
    {
        email: "bella.hunter@test.com",
        username: 'bella.hunter',
        gender: "female",
        dateOfBirth: "1992-03-12",
        name: "Bella Hunter",
        created: "2024-08-11",
        lastActive: "2024-09-02",
        description: "Bella, a documentary filmmaker, travels frequently to capture powerful stories about climate change. When not editing videos, she enjoys paddle boarding, indie films, and discovering hidden cafes in her city.",
        city: "Nanaimo",
        country: "Canada",
        image: "/images/f3.jpeg"
    },
    {
        email: "zoe.richards@test.com",
        username: 'zoe.richards',
        gender: "female",
        dateOfBirth: "1993-09-17",
        name: "Zoe Richards",
        created: "2024-08-15",
        lastActive: "2024-08-31",
        description: "Zoe is a marine biologist passionate about ocean life. She regularly volunteers for beach cleanups and leads educational workshops for children. She loves scuba diving and underwater photography.",
        city: "White Rock",
        country: "Canada",
        image: "/images/f4.jpeg"
    },
    {
        email: "nina.clarke@test.com",
        username: 'nina.clarke',
        gender: "female",
        dateOfBirth: "1990-11-09",
        name: "Nina Clarke",
        created: "2024-08-13",
        lastActive: "2024-09-03",
        description: "Nina is a culinary artist who runs a fusion cuisine food truck. She’s known for her creative dishes that blend traditional recipes with modern flair. Nina also enjoys street photography and traveling to taste international flavors.",
        city: "Abbotsford",
        country: "Canada",
        image: "/images/f5.jpeg"
    },
    {
        email: "brandon.meyer@test.com",
        username: 'brandon.meyer',
        gender: "male",
        dateOfBirth: "1991-05-22",
        name: "Brandon Meyer",
        created: "2024-08-10",
        lastActive: "2024-09-03",
        description: "Brandon is a drone operator and videographer who specializes in cinematic aerial shots for outdoor events. In his free time, he enjoys mountain biking, brewing craft beer, and camping under the stars.",
        city: "Chilliwack",
        country: "Canada",
        image: "/images/m1.jpeg"
    },
    {
        email: "lucas.patel@test.com",
        username: 'lucas.patel',
        gender: "male",
        dateOfBirth: "1993-12-06",
        name: "Lucas Patel",
        created: "2024-08-11",
        lastActive: "2024-08-30",
        description: "Lucas is a data analyst with a love for puzzles and logic games. He spends weekends volunteering at local tech bootcamps to mentor students and occasionally DJs at small local events.",
        city: "Kamloops",
        country: "Canada",
        image: "/images/m2.jpeg"
    },
    {
        email: "tyler.hughes@test.com",
        username: 'tyler.hughes',
        gender: "male",
        dateOfBirth: "1994-08-03",
        name: "Tyler Hughes",
        created: "2024-08-18",
        lastActive: "2024-09-01",
        description: "Tyler, a firefighter and part-time paramedic, is passionate about community safety and public awareness campaigns. He enjoys car restoration projects and mentoring teens interested in emergency services.",
        city: "Prince George",
        country: "Canada",
        image: "/images/m3.jpeg"
    },
    {
        email: "noah.walters@test.com",
        username: 'noah.walters',
        gender: "male",
        dateOfBirth: "1992-10-21",
        name: "Noah Walters",
        created: "2024-08-20",
        lastActive: "2024-09-04",
        description: "Noah is a wildlife photographer who has spent years capturing the majestic beauty of Canada’s national parks. When home, he enjoys editing photos, giving school talks, and running nature photography workshops.",
        city: "Nelson",
        country: "Canada",
        image: "/images/m4.jpeg"
    },
    {
        email: "owen.barker@test.com",
        username: 'owen.barker',
        gender: "male",
        dateOfBirth: "1995-06-16",
        name: "Owen Barker",
        created: "2024-08-22",
        lastActive: "2024-09-02",
        description: "Owen, a game developer, spends his time building immersive virtual worlds. He’s a VR enthusiast, board game collector, and often hosts LAN parties for his friends on weekends.",
        city: "Penticton",
        country: "Canada",
        image: "/images/m5.jpeg"
    }
];
